imports:
    - { resource: config.yml }



doctrine:
    dbal:
        url: "%env(DATABASE_URL)%"
        host: 'ec2-46-137-97-96.eu-west-1.compute.amazonaws.com'
        password: '0653356af7a2249641e7aa0157dd7d468885d381f8c2c6f330c5f0c3ae8b58b5'
        dbname: 'da19e0k5nndu9m'
        user: 'dsbceycpavpplk'
        port: '5432'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

monolog:
    handlers:
        main:
            type: stream
            action_level: error
            handler: nested
        nested:
            type: stream
            path: 'php://stderr'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
