imports:
    - { resource: config.yml }



doctrine:
    dbal:
        url: "%env(DATABASE_URL)%"
        driver: '%env(SYMFONY_BD_DRIVER)%'
        host: '%env(SYMFONY_BD_HOST)%'
        port: '%env(SYMFONY_BD_PORT)%'
        dbname: '%env(SYMFONY_BD_NAME)%'
        user: '%env(SYMFONY_BD_USER)%'
        password: '%env(SYMFONY_BD_PASS)%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

monolog:
    handlers:
        main:
            action_level: error
            handler: nested
        nested:
            type: stream
            path: 'php://stderr'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
